### ISSUE TITLE
SendMessageImage and SendMessageBroadcastImage

### ISSUE THREAD

**Issue by divieirasilva** [mgp25/Chat-API-.NET#10]
When sending images using SendMessageImage or SendMessageBroadcastImage, the API freezes and there is no response.

**Comment by poma** [comment]
Do all networking on background thread

**Comment by divieirasilva** [comment]
Even if i do all the networking on a background thread or async task the thread or task freezes. The problem is I can't send images.

**Comment by w00000w5** [comment]
Try send without polls messages 

It's working

**Comment by singhvibhuti** [comment]
even i am also able to send images, please advice

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API-NET
