### ISSUE TITLE
How to keep Live for ever

### ISSUE THREAD

**Issue by Abtab** [mgp25/Chat-API-.NET#11]
Hi @mgp25 .
WhatsAPINet Log in Disconnects after 3 seconds. How to keep live it for whole day?

Regards

**Comment by yniv** [comment]
After 3 seconds... sounds like you are doing something wrong. Any error message when disconnects?

**Comment by Abtab** [comment]
No message.. i am not doing anything wrong.. if Your application will remain idle without doing anything.. then whats disconnects app from its end.. as in official client you can see. How to avoid that?

**Comment by yniv** [comment]
Yes, I know. But 3 seconds is way to fast for idle disconnects. Something is probably hapening. have you overridden the ondisconnect event and looked what was the exception? 
Anyway, i removed the timeout from the sockets(see whatsnetwork.cs connect() method). Also, I send active every couple of minutes randomly. I don't have any disconnections.

**Comment by Abtab** [comment]
No didnt overwrite anything .. Thanks . I will do that.. How you send active regularily.. Do you check for Status or just a call after a couple of minures?

**Comment by yniv** [comment]
I just call every 3-5 minutes

**Comment by alijundi** [comment]
Hi guys I have a disconnection problem when in Idle. I tried the methods above but no luck. I just want to be online and listen for incoming messages. Any suggestions.. THNX in advance

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API-NET
