### ISSUE TITLE
Send Image with caption

### ISSUE THREAD

**Issue by Abtab** [mgp25/Chat-API-.NET#13]
Hi tried sending image with caption.. but not working.
I have updated code but still its not adding caption. please have a look on my code and correct me if i am wrong some where:

In `whatsapp.cs` i have added caption parameter to method:

```c#
 protected WaUploadResponse UploadFile(string b64hash, string type, long size, byte[] fileData, string to, string contenttype, string extension,string caption)
        {
            ProtocolTreeNode media = new ProtocolTreeNode("media", new KeyValue[] {
                new KeyValue("hash", b64hash),
                new KeyValue("type", type),
                new KeyValue("size", size.ToString()),
             new KeyValue("caption", caption )
            });
            string id = TicketManager.GenerateId();
            ProtocolTreeNode node = new ProtocolTreeNode("iq", new KeyValue[] {
                new KeyValue("id", id),
                new KeyValue("to", WhatsConstants.WhatsAppServer),
                new KeyValue("caption", caption ),
                new KeyValue("type", "set"),
               new KeyValue("xmlns", "w:m")
              
            }, media);
            this.uploadResponse = null;
            this.SendNode(node);
```

others methods updated are:

```c#
  public void SendMessageImage(string to, byte[] ImageData, ImageType imgtype,string caption)
        {
            FMessage msg = this.getFmessageImage(to, ImageData, imgtype,caption );
            if (msg != null)
            {
                this.SendMessage(msg);
            }
        }




       protected FMessage getFmessageImage(string to, byte[] ImageData, ImageType imgtype,string caption)
        {
            string type = string.Empty;
            string extension = string.Empty;
            switch (imgtype)
            {
                case ImageType.PNG:
                    type = "image/png";
                    extension = "png";
                    break;
                case ImageType.GIF:
                    type = "image/gif";
                    extension = "gif";
                    break;
                default:
                    type = "image/jpeg";
                    extension = "jpg";
                    break;
            }
            
            //create hash
            string filehash = string.Empty;
            using(HashAlgorithm sha = HashAlgorithm.Create("sha256"))
            {
                byte[] raw = sha.ComputeHash(ImageData);
                filehash = Convert.ToBase64String(raw);
            }

            //request upload
            WaUploadResponse response = this.UploadFile(filehash, "image", ImageData.Length, ImageData, to, type, extension,caption );

            if (response != null && !String.IsNullOrEmpty(response.url))
            {
                //send message
                FMessage msg = new FMessage(to, true)
                {
                    media_wa_type = FMessage.Type.Image,
                    media_mime_type = response.mimetype,
                    media_name = response.url.Split('/').Last(),
                    media_size = response.size,
                    media_url = response.url,
                    binary_data = this.CreateThumbnail(ImageData)
                };
                return msg;
            }
            return null;
        }
```
 

also updated in `tokenMap.cs` class. 

Please update me If i am wrong some where.

**Comment by mgp25** [comment]
@Abtab post here debug nodes

**Comment by Abtab** [comment]
This is debug print.. but cant find caption in this .. you cant see in above code i added caption


RECVD: <iq from="8613025531436@s.whatsapp.net" id="last_14" type="result">
RECVD:   <query seconds="246"></query>
RECVD: </iq>

RECVD: <iq from="s.whatsapp.net" id="1427735751-15" type="result">
RECVD:   <media url="https://mmi642.whatsapp.net/u/DYZjfnEkY2BmmuVBtwzI9wsXYswABRKEpapQqg/AuLlR8HI4TSMQT8813MT5HhcuY4iD-4RY11UngATQGSc" ip="169.53.29.133"></media>
RECVD: </iq>

SENT: <message to="918054595391@s.whatsapp.net" type="media" id="1427735751-16">
SENT:   <x xmlns="jabber:x:event">
SENT:     <server></server>
SENT:   </x>
SENT:   <media xmlns="urn:xmpp:whatsapp:mms" type="image" file="AuLlR8HI4TSMQT8813MT5HhcuY4iD-4RY11UngATQGSc.jpg" size="9805" url="https://mmi642.whatsapp.net/d/AuLlR8HI4TSMQT8813MT5HhcuY4iD-4RY11UngATQGSc.jpg" encoding="raw">--3383 byte--</media>
SENT:   <offline></offline>
SENT: </message>

SENT: <iq id="last_17" type="get" to="8613025531436@s.whatsapp.net" xmlns="jabber:iq:last">
SENT:   <query></query>
SENT: </iq>

RECVD: <ack from="918054595391@s.whatsapp.net" id="1427735751-16" class="message" t="1427735821"></ack>
Message 1427735751-16 to 918054595391@s.whatsapp.net received by server

RECVD: <iq from="8613025531436@s.whatsapp.net" id="last_17" type="result">
RECVD:   <query seconds="276"></query>
RECVD: </iq>

RECVD: <receipt from="918054595391@s.whatsapp.net" id="1427735751-16" t="1427735826"></receipt>
Message 1427735751-16 to 918054595391@s.whatsapp.net received by client

SENT: <ack to="918054595391@s.whatsapp.net" class="receipt" id="1427735751-16" type="delivery"></ack>

**Comment by Abtab** [comment]
![image](https://cloud.githubusercontent.com/assets/10356321/6902418/62e0a046-d731-11e4-96ef-bf30ad524836.png)

**Comment by Abtab** [comment]
Hi..

Wating for positive reply..

Thanks in advance :)

Regards

**Comment by assegaf** [comment]
@Abtab 
try to think hard to add caption here ..
....
[/media]
SENT:   [offline][/offline]
SENT:  [caption]My mind already think hard[/caption]
SENT: [/message]

**Comment by Abtab** [comment]
btw if you were not interested to help, then no need of efforts. If i am expecting positive reply then what is problem with you?
Appreciate your Negativity. Thanks

**Comment by mgp25** [comment]
@Abtab the nodes are outdated, ill be updating when i have some free time.

You can compare nodes with WhatsAPI Official.

Regards

**Comment by Abtab** [comment]
@mgp25 . I will compare with WhatsAPI Official. I compared this but there is some mismatch> now i will try again.

Thanks for the reply

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API-NET

**Comment by winventum** [comment]
Hello Abtab
Please let me know if you have solved your issue sending images with captions. Also, I would like to ask you if you could share your code of sending images (without captions); I have tried so many ways with no success.
Regards,

**Comment by gahlotkrishan** [comment]
@Abtab

**Comment by gahlotkrishan** [comment]
protected void SendImageWithCaption(string to, byte[] ImageData, ImageType imgtype,string Caption=null)
        {
            FMessage message = this.getFmessageImage(to, ImageData, imgtype);
            if (message != null)
            {
                ProtocolTreeNode node;
                if (FMessage.Type.System == message.media_wa_type)
                {
                    throw new SystemException("Cannot send system message over the network");
                }

                List<KeyValue> list = new List<KeyValue>(new KeyValue[] { new KeyValue("xmlns", "w:m"), new KeyValue("type", FMessage.GetMessage_WA_Type_StrValue(message.media_wa_type)) });

                byte[] data = message.binary_data;
                if ((data == null) && !string.IsNullOrEmpty(message.data))
                {
                    try
                    {
                        data = Convert.FromBase64String(message.data);
                    }
                    catch (Exception)
                    {
                    }
                }
                if (data != null)
                {
                    list.Add(new KeyValue("encoding", "raw"));
                }
                if (message.media_wa_type == FMessage.Type.Image || message.media_wa_type == FMessage.Type.Video)
                    list.Add(new KeyValue("caption", Caption));
                node = new ProtocolTreeNode("media", list.ToArray(), null, data);

                this.SendNode(GetMessageNode(message, node, false));
            }
        }

**Comment by winventum** [comment]
Hello @gahlotkrishan, thanks for your both answers, but not sure which one do I have to implement?

I only have implemented the SendImageWithCaption function (not ```protected```, but ```public```) and didn´t receive the image. 

Please find below the log:

```xml
1 tx <presence type="subscribe" to="3***********@s.whatsapp.net"></presence>
2 tx <chatstate to="3***********@s.whatsapp.net">
3 tx   <composing></composing>
4 tx </chatstate>
5 tx <iq id="1436795458-2" to="s.whatsapp.net" type="set" xmlns="w:m">
6 tx   <media hash="c7hGwTb5YzODTdkTwBdC2sWHP3K4sUazCdGO9ugfDKE=" type="image" size="6573"></media>
7 tx </iq>
8 rx <presence from="3***********@s.whatsapp.net"></presence>
9 rx <iq from="s.whatsapp.net" id="1436795458-2" type="result">
10 rx   <media url="https://mmi619.whatsapp.net/u/Eg1ykZNX4PPqPWt6MZcDAAL-96YABRrCA3kXJQ/AtfotJLpEscrkPsqXSFlksMO_LuXWTVk5Gq3-PP9qkLs" ip="184.173.204.43"></media>
11 rx </iq>
12 tx <message to="3***********@s.whatsapp.net" type="media" id="1436795458-3" t="1436795459">
13 tx   <media xmlns="w:m" type="image" encoding="raw" caption="Tags: test, hit, check">--1841 byte--</media>
14 tx </message>
15 tx <chatstate to="3***********@s.whatsapp.net">
16 tx   <paused></paused>
17 tx </chatstate>
18 tx <receipt to="3***********@s.whatsapp.net" id="1436789711-14" type="read"></receipt>
19 rx <ack from="3***********@s.whatsapp.net" id="1436789711-14" class="receipt" type="read"></ack>
```
If you compare the tx data (at line 12) with normal image sending, you will see that in the ```<message>``` tag are missing some attributes like "file" and "url".

Please let me know your thoughts about that.

Will check your first suggestion about SendMessageWithMedia function and let you know.

Regards,
