### ISSUE TITLE
Programmatically how to post a message to a user whatsapp account

### ISSUE THREAD

**Issue by Tapasghosh** [mgp25/Chat-API-.NET#17]
In my project needs to send message to user whatsapp account.

To do this , I have reasearch and found that whatsAppApi is available.

So I have used it. While I have debugging the code it shows message is posted and returned the delivery key id where as actually message is not sent to that account.

I have used ASP.Net C# for development.  Can any one help me to find out the error.

For more information I have attached my code below.

var tmpEncoding = Encoding.UTF8;
               System.Console.OutputEncoding = Encoding.Default;
               System.Console.InputEncoding = Encoding.Default;
               string nickname = "sou***dip";
               string sendernumber = "917****14557";  // Mobile number with country code (but without + or 00)
               string password = "66***2"; //v2 password
               string targetnumber = "9196****4739";// Mobile number to send the message to
 
WhatsApp wa = new WhatsApp(sendernumber, password, nickname, true);
               wa.Connect();
 
WhatsUserManager usrMan = new WhatsUserManager();
           var tmpUser = usrMan.CreateUser(targetnumber , "User");
 
string sm= wa.SendMessage(tmpUser.GetFullJid(), "Hi");

**Comment by mdeker** [comment]
I think you need to call Login function before send anything, as i see in your code you only connect. You can see example in demo project.

**Comment by Tapasghosh** [comment]
Hi ,
as per your suggestion I have rewrite the code . First connect then log in and then process for sending message. Here while I step for login I got error message. "Invalid base 64 string". For more information I have just write down code again . Please let me know how I solve it.

 var tmpEncoding = Encoding.UTF8;
                System.Console.OutputEncoding = Encoding.Default;
                System.Console.InputEncoding = Encoding.Default;
                string nickname = "sou***dip";
                string sendernumber = "9175****4557";  // Mobile number with country code (but without + or 00)
                string password = "66***2"; //v2 password
                string targetnumber = "9196****4739";// Mobile number to send the message to

                WhatsApp wa = new WhatsApp(sendernumber, password, nickname, true);
                wa.Connect();
                byte[] nextChallenge = null;
                nextChallenge = Convert.FromBase64String(targetnumber);
                wa.Login(nextChallenge);  //From here I got error message 
                string sm= wa.SendMessage(tmpUser.GetFullJid(), 'hi');

if I send  wa.Login();  instead wa.Login(nextChallenge);  then I also got error message.
Please help me to find the answer. I am waiting for your reply.

**Comment by mdeker** [comment]
it is issue of previous vertion, download up to date vertion or post here log

**Comment by Tapasghosh** [comment]
Hello,
From Package Manager console I have installed WhatsAppAPI 15.1.9.
After this I got the error "Invalid length for a Base-64 char array or string.".
Kindly advise me .

**Comment by Tapasghosh** [comment]
Hello ,
For more information I want to inform you that as Password I have used the code which I got in my mobile in a sms while registration the whatsapp. Is it ok or not ?
Please advise . I am waiting for your reply.
Thanks in advance.

**Comment by hypertech** [comment]
You need to create your acc with registration tool, sms is not a Password, it is tool to get it. Check registration functions in demos

**Comment by Tapasghosh** [comment]
using this api I tried to register a number but it is not registered shows error "Status: Failed , Use older version". Whereas I have downloaded the latest whatsapi version and use it .
Please advise me and can you send me the whatsappapi with latest version.

**Comment by mdeker** [comment]
Try to use php api or python one to register

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API-NET
