### ISSUE TITLE
Cannot evaluate expression because a native frame is on top of the call stack.

### ISSUE THREAD

**Issue by momenimohammad23** [mgp25/Chat-API-.NET#18]
hi 
sometime when I connect to whats app and use wa.sendcreategroupchat
api freeze om wa.poolmessages();
and when I use wa.Connectionstatus in the Immediated Window I get this :
"Cannot evaluate expression because a native frame is on top of the call stack."

Note : just sometime occur this issue maybe after 100 login ...

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API-NET
