### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by mmalbergier** [mgp25/Chat-API-.NET#19]
Is it possible that I receive the
< failure >< not-authorized >< /not-authorized >< / failure >
But, if I go again to the cell phone and register using the Whatsapp APP, it works?
If the phone gets blocked using the API, is it supposed that it shouldn't work in the phone?

**Comment by alijundi** [comment]
I think it is because the password you are supplying is incorrect. you should see blocked if your phone is blocked and not not-authorized

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API-NET
