### ISSUE TITLE
Whatsapi doesn't login to server

### ISSUE THREAD

**Issue by F0b0s** [mgp25/Chat-API-.NET#2]
I can't login.

The problem that my connection fails on `WhatsSendBase.Login` method on `SendData` call with `SocketException and exception code ConnectionAborted`. I thought about it and have a question, we use 443 port but work with simple TCP stream without SslStream. Is it correct? I suppose that WhatsApp server expect Ssl handshake from us, but we send WhatsApp protocol data and he abort connection. Can you help me?

**Comment by mgp25** [comment]
@F0b0s I'll send updates tonight and tomorrow that will fix login with newer versions and features.

Regards

**Comment by mgp25** [comment]
@F0b0s you can try now. Update with the latest commit and send e feedback.

Regards

**Comment by F0b0s** [comment]
Hello, thanks for your help. I got your update but it still doesn't work for me. It's brief explanation:
![image](https://cloud.githubusercontent.com/assets/993960/5836037/b4a80aae-a180-11e4-851e-62d5b80840a5.png)
Here at one of this SendData i recieve SocketException
![image](https://cloud.githubusercontent.com/assets/993960/5836063/210d8494-a181-11e4-8d39-f054ebdcf142.png)
I'm trying to understand is it caused by my local environment.

**Comment by cooler-farmer** [comment]
I have a similar error. For me it doesn't receive any data after login, so it stucks in the while loop and doesn't login
I used an old dll that work

**Comment by F0b0s** [comment]
*I used an old dll that work*
What do you mean? Do you know which version of this dll can successfully login and send/receive messages?

**Comment by cooler-farmer** [comment]
@F0b0s I don't know which version, sorry

**Comment by F0b0s** [comment]
@mgp25 Hello, may i ask you about your plans about this project? It seems to me that it doesn't work correctly.

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API-NET
