### ISSUE TITLE
ReceiptAcks

### ISSUE THREAD

**Issue by alijundi** [mgp25/Chat-API-.NET#20]
Hey guys,

I am not sure but I am receiving a bunch of delivery and read messages from server every time I connect and login! Is it because the API does not send the Delivery and Read Acks? If so, any suggestion on how to add this feature directly to the API.

**Comment by matteocontrini** [comment]
Wrong acks are being sent:
* https://github.com/hidespb/node-whatsapi/commit/e144a1ab0cb643ed53968060c86ec862e9c9af54
* https://github.com/mgp25/Chat-API/commit/07d28e15ce1a41793556230f61441d9705119d20
* https://github.com/tgalal/yowsup/pull/756

**Comment by alijundi** [comment]
@matteocontrini I appreciate your input. but can we please reflect the same changes in PHP to Chat-API-NET Repo. Thanks

**Comment by matteocontrini** [comment]
Fix the ack node [here](https://github.com/mgp25/Chat-API-NET/blob/master/WhatsAppApi/Base/WhatsSendBase.cs#L665). Anyway, there are many outdated functions that need to be rewritten. Even sending a message is wrong right now.

**Comment by alijundi** [comment]
hi @matteocontrini  I did a search for SendReceiptAck function and the calling function SendDeliveredReceiptAck but it is not being called at all from the API. If I fix it what good will it do?

**Comment by mgp25** [comment]
Major update coming soon

**Comment by alijundi** [comment]
@mgp25 thanks for the info. I can't wait to see the update. :)

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API-NET
