### ISSUE TITLE
Sync contact take long time in poolmessages 

### ISSUE THREAD

**Issue by beljk** [mgp25/Chat-API-.NET#24]
@mgp25 Dear sir ,,,

I want to sync contact and here is my code

  private void button1_Click(object sender, EventArgs e)
        {
            string[] num={"201018106101","201010432512","201281214102","201004412644","201000967204","201002639112"};
            if (!this.CheckLogin("20121241****", "Niy969EGhSijtgrPD4m9Ur4cig0=", "Adv"))
            {

                MessageBox.Show("Failed login");
                return;
                
            }
            MessageBox.Show("suc login");
            WhatSocket.Instance.SendSync(num, WhatsAppApi.ApiBase.SyncMode.Full, WhatsAppApi.ApiBase.SyncContext.Background, 0, true);
            WhatSocket.Instance.PollMessages();

            MessageBox.Show("Verification done!");
        }
        private void wa_OnGetSyncResult(int index, string sid, Dictionary<string, string> existingUsers, string[] failedNumbers)
        {
            //txt(String.Format("Sync result for {0}:", sid));
            foreach (KeyValuePair<string, string> item in existingUsers)
            {
                if (textBox1.Text.Length == 0)
                {
                    textBox1.Text = item.Key.Substring(1);
                }
                else
                {
                    textBox1.Text += "\r\n" + item.Key.Substring(1);
                }
            }

            foreach (string item in failedNumbers)
            {
                if (textBox2.Text.Length == 0)
                {
                    textBox2.Text = item.Substring(1);
                }
                else
                {
                    textBox2.Text = "\r\n" + item.Substring(1);
                }
            }
        }

then when run the app number login and send sync ok but in poolmessages its take a long time without result 
Thanks

**Comment by skaypc** [comment]
Hi
I have the same issue ! it seams stop main thread on poolmessages ! 
this problem occur some times not always , for example after login with 50 account this issue occur !
did you solve it ?

**Comment by Abtab** [comment]
Oh God!!! All are spammers here.

**Comment by alijundi** [comment]
Hi guys. @mgp25 announced that there is a major update coming soon. so keep calm and wait.

**Comment by beljk** [comment]
@skaypc  No ... @mgp25 hey man where are you ?

**Comment by mgp25** [comment]
@beljk i'll update all code this weekend or so.

**Comment by beljk** [comment]
@mgp25 OK man :)

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API-NET
