### ISSUE TITLE
How to check if the message was delivered?

### ISSUE THREAD

**Issue by EgyptianM** [mgp25/Chat-API-.NET#29]
Hello mgp25

How can I check if the message was delivered or not?
and is it possible to know if user read it or not?
and how to know if msg sent or not because somethimes it send but I don't recieve it
thank you in advance

**Comment by farisyusry** [comment]
@EgyptianM  you can follow whattest project

**Comment by mgp25** [comment]
@EgyptianM use events

Regards

**Comment by EgyptianM** [comment]
thank you all :)
