### ISSUE TITLE
Read receipts are not working

### ISSUE THREAD

**Issue by poma** [mgp25/Chat-API-.NET#3]
When I receive read receipt I get 

    <receipt from="request" preview="digest" s.us="order" digest="name" s.whatsapp.net="id"></receipt>

instead of

    <receipt from="123@s.whatsapp.net" id="1494720830-0" retry="2" offline="2" t="1494730671"></receipt>

If I replace `TokenMap.cs` and `BinTreeNodeWriter.cs` from @shirioko's fork it works fine. To reproduce this bug just send a message with `WhatsTest` project and wait until recipient receives it.

**Comment by mgp25** [comment]
@poma im going to check it now.

Regards

**Comment by mgp25** [comment]
Its because the other repo its using an outdated TokenMap, this one from here its the newer TokenMap, somehow it doesnt detect and use it correctly, ill check it and fix it

Regards

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API-NET
