### ISSUE TITLE
Can't send images

### ISSUE THREAD

**Issue by observer1** [mgp25/Chat-API-.NET#4]
Hi
I'm trying to send an image, I'm using the whatsappport app I just replaced the call to SendMessage with SendMessageImage.
I have tried 3 forks and all of them stay a lot of time in the loop at WhatsApp.cs:260 and no response is received when the loop finish the member uploadResponse is null and an exception is thrown

Can you help me with this

thanks

**Comment by mgp25** [comment]
@observer1 i have to check it and update some code, meanwhile you can use WhatsAPI Official (PHP)

Regards

**Comment by singhvibhuti** [comment]
i am unable to send image.'

provided below are the sample code which i am calling

 System.Drawing.Image img = System.Drawing.Image.FromFile(filename);
                        byte[] b = imageToByteArray(img);
                        _instance.SendMessageImage("91" + c.MobileNo, b, ApiBase.ImageType.PNG);

**Comment by brittson** [comment]
Use all networking on background thread and dont use poll message

**Comment by singhvibhuti** [comment]
Can you please provide me sample code and .method where i have to do changes.

**Comment by singhvibhuti** [comment]
I debug the application and found that image is successfully get uploaded on whatsapp server, receiving url n all but not receiving the same on mobile.

I even tried while commenting pollmessages.

When i try to access the Url generated by api it gives me message invalid links, i am getting images when i am using portable pidgin.

Please help me

**Comment by singhvibhuti** [comment]
I have resolved the issue, while debug i come to know that in SendMessageImage numer was not getting concert to JID i did it manually and passed the JID and it start working.

Also i have verified, Image, Audio and Video working smoothly

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API-NET
