### ISSUE TITLE
Polling messages from two or more threads (different numbers) simultaneously

### ISSUE THREAD

**Issue by yniv** [mgp25/Chat-API-.NET#6]
I have a multi-threaded server that polls messages for multiple phones numbers using this sdk.
My problem is that after a while(couple of minutes or less) i recieve stream:error messages from whatsapp. Does anybody know about this problem? is the sdk thread-safe? meaning i can use several instances of it simultaneously?
Any help will be appreciated. Thanks!

**Comment by poma** [comment]
Probably servery disconnects you because you are inactive for some time (30-60 seconds)

**Comment by yniv** [comment]
No, I don't disconnect... i get stream:error messages. Also, i have a complete proccess which handle disconnections(sendint active every x secs and so).
Also, when i poll messages for only one number from one thread at a time it works as ussuall.

**Comment by yniv** [comment]
I think i have found the problem and it is in the TicketManager and TicketCounter classes which are both
designed as singletons... Thus, when requesting for next tickets from multiple threads continuity of the tickets is broken and WhatsApp sends error...
I'm implementing a complete solution for this to make this SDK to be Thread-Safe. If someone is interested tell me and i'll post it here.

**Comment by hpatel4u** [comment]
@yniv i am getting the same error, please suggest how do i solve.

**Comment by poma** [comment]
@hpatel4u if you are getting `<stream:error><ping></ping></stream:error>` then you are probably disconnected due to inactivity. If you are getting `xml-not-well-formed` error then you are probably writing in multiple threads to the same connection. This can be fixed by using a lock in `WhatsAppBase.SendNode()`:
    protected void SendNode(ProtocolTreeNode node)
    {
        lock (this.BinWriter)
            this.SendData(this.BinWriter.Write(node));
    }

**Comment by hpatel4u** [comment]
@yniv & @poma thank you, i will check and update you on it.

Thanks again!

**Comment by hpatel4u** [comment]
@poma its worked :+1:

**Comment by hpatel4u** [comment]
Hi Guys, 

I am getting socket not connected while sending media.

Any suggestion.

Regards,

**Comment by yniv** [comment]
@hpatel4u this sound like unrelated bug. @poma your solution solves sending message for one number from 2 or more different threads. My solution solves sending and receiving messages for 2 or more numbers on one application. 

Anyway, here is the new ticketmanager. It is a partial fix, you should fix all the places calling this class (i don't know how to post changes in github) and add a class instance to WhatsApp class:
namespace WhatsAppApi.Helper
{
    public class TicketManager
    {        
        private string IdBase {get; set; }
        private int id = -1;
        
        public TicketManager()
        {
            IdBase = Func.GetNowUnixTimestamp().ToString();
        }

        public string GenerateId()
        {            
            return (IdBase + "-" + NextTicket());
        }

        public int NextTicket()
        {
            return Interlocked.Increment(ref id);
        }

        public string MakeId(string prefix)
        {
            int num = NextTicket();
            return (prefix + num);
        }
    }    
}

**Comment by hpatel4u** [comment]
@yniv thank you, can you please share a code to check once (to run multiple sender using single application).

Thanks Again

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API-NET
