### ISSUE TITLE
Using the sample code i am unable to recieve messages

### ISSUE THREAD

**Issue by CJM753** [mgp25/Chat-API-.NET#8]
I am able to send messages and receive them on whatsapp

Looking into this it appears to be expecting parameters that are not there when receiving the messages. Such as in the chatstate node and the message node.

![example](https://cloud.githubusercontent.com/assets/8493692/6620588/928e54f8-c8c9-11e4-8331-4028284c3ddb.jpg)

Any Idea what is going wrong?

**Comment by netomarquis** [comment]
I am having this problem too... any idea how to solve it?

**Comment by mgp25** [comment]
Use events, if you are in debug mode, you will see the messages in the nodes. I have to update .NET btw

**Comment by netomarquis** [comment]
It worked.

The php project works fine? I.e. these version doesnt send the "read" alert for the server, it works on php?

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API-NET
